apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: session-prom
  namespace: monitoring
  labels:
    app: session-prom-monitor
    monitoring: prometheus-exporter
spec:
  selector:
    matchLabels:
      run: session-prometheus
  namespaceSelector:
    matchNames:
    - test
  endpoints:
  - interval: 5s
    path: /metrics